/**
 * Yalnızca demo sunumu içindir. Bu dosyadaki hiçbir şey gerçek bir kuruma ait
 * değildir ve production'da gösterilmemelidir.
 *
 * Bugün hâlâ production'da da okunuyor; demo moduna hapsedilmesi Faz E5'in
 * sıradaki dilimidir. Buraya yeni veri eklerken bunu aklında tut.
 */
import type {
  Automation,
  AttendanceState,
  ClassGroup,
  DayPlanEvent,
  DayPlanRole,
  DayPlanTask,
  Homework,
  PaymentRow,
  Role,
  ScheduleItem,
  Student,
} from "./types";

export const students: Student[] = [
  {
    id: "stu-001",
    name: "Zeynep Kaya",
    code: "YKS-24018",
    group: "YKS 12-A",
    branch: "Çorlu Şube",
    parent: "Murat Kaya",
    attendance: 96,
    score: 84,
    homework: 8,
    payment: "Güncel",
    risk: "Dengeli",
    isMock: true,
  },
  {
    id: "stu-002",
    name: "Efe Demir",
    code: "YKS-24027",
    group: "YKS 12-A",
    branch: "Çorlu Şube",
    parent: "Elif Demir",
    attendance: 88,
    score: 71,
    homework: 5,
    payment: "Güncel",
    risk: "Takip gerekli",
    isMock: true,
  },
  {
    id: "stu-003",
    name: "Derin Yıldız",
    code: "YKS-24031",
    group: "YKS 12-B",
    branch: "Çorlu Şube",
    parent: "Selin Yıldız",
    attendance: 94,
    score: 78,
    homework: 7,
    payment: "Takip gerekli",
    risk: "Dengeli",
    isMock: true,
  },
  {
    id: "stu-004",
    name: "Aras Öztürk",
    code: "YKS-24042",
    group: "YKS 12-B",
    branch: "Çorlu Şube",
    parent: "Berna Öztürk",
    attendance: 82,
    score: 63,
    homework: 3,
    payment: "Güncel",
    risk: "Takip gerekli",
    isMock: true,
  },
  {
    id: "stu-005",
    name: "Nisan Akın",
    code: "YKS-24049",
    group: "YKS 11-C",
    branch: "Çorlu Şube",
    parent: "Emre Akın",
    attendance: 98,
    score: 89,
    homework: 9,
    payment: "Güncel",
    risk: "Dengeli",
    isMock: true,
  },
];

export const classes: ClassGroup[] = [
  {
    id: "cls-1",
    name: "YKS 12-A",
    program: "Sayısal hazırlık",
    mentor: "Merve Karaca",
    studentCount: 18,
    attendance: 94,
    nextLesson: "Bugün · 10:00 Matematik",
    isMock: true,
  },
  {
    id: "cls-2",
    name: "YKS 12-B",
    program: "Eşit ağırlık hazırlık",
    mentor: "Bora Ekin",
    studentCount: 16,
    attendance: 89,
    nextLesson: "Bugün · 11:30 Türkçe",
    isMock: true,
  },
  {
    id: "cls-3",
    name: "YKS 11-C",
    program: "Temel yeterlilik",
    mentor: "Merve Karaca",
    studentCount: 20,
    attendance: 97,
    nextLesson: "Yarın · 09:00 Fizik",
    isMock: true,
  },
];

export const schedule: ScheduleItem[] = [
  {
    time: "09:00",
    title: "TYT Matematik",
    group: "YKS 12-A",
    teacher: "Merve Karaca",
    room: "Derslik 204",
    tone: "bg-sky-50 text-sky-700 ring-sky-100",
    isMock: true,
  },
  {
    time: "10:30",
    title: "Problem Atölyesi",
    group: "YKS 12-B",
    teacher: "Bora Ekin",
    room: "Derslik 105",
    tone: "bg-violet-50 text-violet-700 ring-violet-100",
    isMock: true,
  },
  {
    time: "13:00",
    title: "Rehberlik Görüşmesi",
    group: "Zeynep Kaya",
    teacher: "Merve Karaca",
    room: "Görüşme Odası",
    tone: "bg-amber-50 text-amber-700 ring-amber-100",
    isMock: true,
  },
  {
    time: "14:30",
    title: "TYT Deneme Analizi",
    group: "YKS 11-C",
    teacher: "Seda Kılıç",
    room: "Etüt Salonu",
    tone: "bg-emerald-50 text-emerald-700 ring-emerald-100",
    isMock: true,
  },
];

export const initialAutomations: Automation[] = [
  {
    id: "auto-1",
    title: "Aday kayıt takibi",
    description:
      "Yeni aday kaydını danışmana atar, ilk görüşme tamamlanana kadar takip görevi açar.",
    trigger: "Yeni aday formu geldiğinde",
    impact: "4 aday takipte",
    active: true,
    category: "Kayıt",
    isMock: true,
  },
  {
    id: "auto-2",
    title: "Devamsızlık bildirimi",
    description:
      "Yoklamada görünmeyen öğrenci için veliye onaylı bildirim ve rehberlik görevi oluşturur.",
    trigger: "Yoklama tamamlandığında",
    impact: "Bugün 3 öğrenci işlendi",
    active: true,
    category: "Devam",
    isMock: true,
  },
  {
    id: "auto-3",
    title: "Deneme sonucu takibi",
    description:
      "Deneme sonucu yayınlandığında öğrenci, veli ve öğretmen için takip özeti hazırlar.",
    trigger: "Sınav sonucu yayınlandığında",
    impact: "Son 7 gün · 42 özet",
    active: true,
    category: "Akademik",
    isMock: true,
  },
  {
    id: "auto-4",
    title: "Veli iletişim merkezi",
    description:
      "Duyuru ve görüşme taslaklarını doğru sınıf veya veli grubuna yönlendirir.",
    trigger: "İletişim görevi oluşturulduğunda",
    impact: "2 görüşme önerisi bekliyor",
    active: false,
    category: "İletişim",
    isMock: true,
  },
];

export const paymentRows: PaymentRow[] = [
  {
    student: "Zeynep Kaya",
    plan: "YKS Sayısal Paket",
    due: "05 Eylül 2026",
    amount: "₺7.200",
    status: "Güncel",
    isMock: true,
  },
  {
    student: "Derin Yıldız",
    plan: "YKS Eşit Ağırlık Paket",
    due: "28 Ağustos 2026",
    amount: "₺6.800",
    status: "Hatırlatma gerekli",
    isMock: true,
  },
  {
    student: "Aras Öztürk",
    plan: "YKS Eşit Ağırlık Paket",
    due: "18 Ağustos 2026",
    amount: "₺6.800",
    status: "Gecikme riski",
    isMock: true,
  },
];

export const initialHomework: Homework[] = [
  {
    id: "hw-1",
    classGroup: "YKS 12-A",
    subject: "Matematik",
    title: "Fonksiyonlarda Uygulama Seti",
    description:
      "Fonksiyon türleri ve grafik yorumlama üzerine 20 soruluk uygulama seti.",
    assignedBy: "Merve Karaca",
    assignedDate: "18 Ağustos 2026",
    dueDate: "22 Ağustos 2026",
    status: "Süresi Doldu",
    isMock: true,
  },
  {
    id: "hw-2",
    classGroup: "YKS 12-A",
    subject: "Geometri",
    title: "Üçgenlerde Alan Problemleri",
    description:
      "Üçgende alan bağıntıları ve benzerlik problemlerinden oluşan tekrar kağıdı.",
    assignedBy: "Merve Karaca",
    assignedDate: "20 Ağustos 2026",
    dueDate: "27 Ağustos 2026",
    status: "Aktif",
    isMock: true,
  },
  {
    id: "hw-3",
    classGroup: "YKS 12-A",
    subject: "Türkçe",
    title: "Paragrafta Anlam Çalışma Kağıdı",
    description:
      "Paragrafta anlatım biçimleri ve yardımcı düşünce sorularından oluşan tekrar seti.",
    assignedBy: "Merve Karaca",
    assignedDate: "12 Ağustos 2026",
    dueDate: "19 Ağustos 2026",
    status: "Tamamlandı",
    isMock: true,
  },
  {
    id: "hw-4",
    classGroup: "YKS 11-C",
    subject: "Fizik",
    title: "Kuvvet ve Hareket Soru Seti",
    description:
      "Newton'un hareket yasaları ve sürtünme kuvveti üzerine problem seti.",
    assignedBy: "Merve Karaca",
    assignedDate: "19 Ağustos 2026",
    dueDate: "26 Ağustos 2026",
    status: "Aktif",
    isMock: true,
  },
  {
    id: "hw-5",
    classGroup: "YKS 11-C",
    subject: "Kimya",
    title: "Mol Kavramı Tekrar Testi",
    description:
      "Mol hesaplamaları ve kimyasal tepkimelerde stokiyometri üzerine test.",
    assignedBy: "Merve Karaca",
    assignedDate: "14 Ağustos 2026",
    dueDate: "20 Ağustos 2026",
    status: "Süresi Doldu",
    isMock: true,
  },
  {
    id: "hw-6",
    classGroup: "YKS 12-B",
    subject: "Biyoloji",
    title: "Hücre Bölünmesi Kavram Haritası",
    description:
      "Mitoz ve mayoz bölünme aşamalarını karşılaştıran kavram haritası ödevi.",
    assignedBy: "Bora Ekin",
    assignedDate: "17 Ağustos 2026",
    dueDate: "24 Ağustos 2026",
    status: "Aktif",
    isMock: true,
  },
  {
    id: "hw-7",
    classGroup: "YKS 12-B",
    subject: "Matematik",
    title: "Türev Uygulamaları Deneme Seti",
    description:
      "Türev kuralları ve maksimum-minimum problemlerinden oluşan deneme seti.",
    assignedBy: "Bora Ekin",
    assignedDate: "10 Ağustos 2026",
    dueDate: "17 Ağustos 2026",
    status: "Süresi Doldu",
    isMock: true,
  },
];

export const initialAttendances: Record<string, AttendanceState> = {
  "stu-001": "Katıldı",
  "stu-002": "Katıldı",
  "stu-003": "Geç kaldı",
  "stu-004": "Gelmedi",
  "stu-005": "Katıldı",
};

export const dayPlanTasksByRole: Record<DayPlanRole, DayPlanTask[]> = {
  admin: [
    {
      id: "dpt-a1",
      title: "Ağustos devam ve performans raporu",
      detail: "Şube geneli devam ve akademik özet raporunu hazırla.",
      status: "Planla",
      priority: "Orta",
      category: "Rapor",
      duration: "40 dk",
      dueLabel: "Yarın 09:00",
      isMock: true,
    },
    {
      id: "dpt-a2",
      title: "Yeni dönem sınıf kontenjanları",
      detail: "YKS 11 ve 12 gruplarında boş kontenjanları güncelle.",
      status: "Planla",
      priority: "Düşük",
      category: "Kayıt",
      duration: "20 dk",
      dueLabel: "25 Ağustos",
      isMock: true,
    },
    {
      id: "dpt-a3",
      title: "Çorlu şube haftalık değerlendirme toplantısı",
      detail: "Öğretmen kadrosuyla haftalık başarı ve devam özetini paylaş.",
      status: "Bugün",
      priority: "Yüksek",
      category: "Rapor",
      duration: "45 dk",
      dueLabel: "Bugün 15:00",
      isMock: true,
    },
    {
      id: "dpt-a4",
      title: "Veli şikayeti — Aras Öztürk",
      detail: "Devam durumu hakkında veliyi arayıp bilgilendir.",
      status: "Bugün",
      priority: "Yüksek",
      category: "Veli İletişimi",
      duration: "15 dk",
      dueLabel: "Bugün 11:30",
      isMock: true,
    },
    {
      id: "dpt-a5",
      title: "Ağustos deneme sınavı sonuç analizi",
      detail: "TYT deneme sonuçlarını şube bazında karşılaştır.",
      status: "Odaklan",
      priority: "Yüksek",
      category: "Sınav",
      duration: "60 dk",
      dueLabel: "Bugün 13:00",
      isMock: true,
    },
    {
      id: "dpt-a6",
      title: "Yoklama otomasyon kontrolü",
      detail: "Devamsızlık bildirim otomasyonunun çalıştığını doğrula.",
      status: "Tamamlandı",
      priority: "Orta",
      category: "Yoklama",
      duration: "10 dk",
      dueLabel: "Dün tamamlandı",
      isMock: true,
    },
  ],
  teacher: [
    {
      id: "dpt-t1",
      title: "TYT Matematik konu tekrar planı",
      detail: "Geometri ağırlıklı haftalık tekrar planını hazırla.",
      status: "Planla",
      priority: "Orta",
      category: "Ders Programı",
      duration: "35 dk",
      dueLabel: "26 Ağustos",
      isMock: true,
    },
    {
      id: "dpt-t2",
      title: "YKS 12-A deneme sınavı soru hazırlığı",
      detail: "Hafta sonu denemesi için 20 soruluk ek paket hazırla.",
      status: "Planla",
      priority: "Orta",
      category: "Sınav",
      duration: "50 dk",
      dueLabel: "27 Ağustos",
      isMock: true,
    },
    {
      id: "dpt-t3",
      title: "YKS 12-A yoklama girişi",
      detail: "Sabah dersinin yoklamasını sisteme işle.",
      status: "Bugün",
      priority: "Yüksek",
      category: "Yoklama",
      duration: "10 dk",
      dueLabel: "Bugün 09:00",
      isMock: true,
    },
    {
      id: "dpt-t4",
      title: "Efe Demir velisiyle görüşme",
      detail: "Devam durumu ve ödev takibi hakkında bilgi ver.",
      status: "Bugün",
      priority: "Orta",
      category: "Veli İletişimi",
      duration: "20 dk",
      dueLabel: "Bugün 16:00",
      isMock: true,
    },
    {
      id: "dpt-t5",
      title: "TYT deneme analiz raporu — YKS 11-C",
      detail: "Son deneme sonucunu ders bazlı net grafiğiyle özetle.",
      status: "Odaklan",
      priority: "Yüksek",
      category: "Rapor",
      duration: "45 dk",
      dueLabel: "Bugün 14:30",
      isMock: true,
    },
    {
      id: "dpt-t6",
      title: "Problem atölyesi ders notu paylaşımı",
      detail: "Bugünkü atölye notlarını sınıf grubuna gönder.",
      status: "Tamamlandı",
      priority: "Düşük",
      category: "Ders Programı",
      duration: "15 dk",
      dueLabel: "Dün tamamlandı",
      isMock: true,
    },
  ],
};

export const dayPlanEventsByRole: Record<DayPlanRole, DayPlanEvent[]> = {
  admin: [
    {
      id: "dpe-a1",
      date: "2026-08-21",
      startTime: "10:00",
      endTime: "10:30",
      mode: "Google Meet",
      type: "Veli Görüşmesi",
      title: "Kaya ailesi ile görüşme",
      subtitle: "Zeynep Kaya velisi",
      isMock: true,
    },
    {
      id: "dpe-a2",
      date: "2026-08-21",
      startTime: "13:00",
      endTime: "13:45",
      mode: "Yüz yüze",
      type: "Şube Toplantısı",
      title: "Çorlu şube haftalık toplantı",
      subtitle: "Yönetim ekibi",
      isMock: true,
    },
    {
      id: "dpe-a3",
      date: "2026-08-24",
      startTime: "11:00",
      endTime: "11:30",
      mode: "Google Meet",
      type: "Öğretmen Değerlendirmesi",
      title: "Bora Ekin performans görüşmesi",
      subtitle: "Dönem ortası değerlendirme",
      isMock: true,
    },
    {
      id: "dpe-a4",
      date: "2026-08-27",
      startTime: "09:30",
      endTime: "10:00",
      mode: "Telefon",
      type: "Aday Kayıt Görüşmesi",
      title: "Yeni aday velisi görüşmesi",
      subtitle: "YKS 11. sınıf kaydı",
      isMock: true,
    },
  ],
  teacher: [
    {
      id: "dpe-t1",
      date: "2026-08-21",
      startTime: "13:00",
      endTime: "13:30",
      mode: "Yüz yüze",
      type: "Rehberlik Görüşmesi",
      title: "Zeynep Kaya ile rehberlik görüşmesi",
      subtitle: "Görüşme Odası",
      isMock: true,
    },
    {
      id: "dpe-t2",
      date: "2026-08-21",
      startTime: "16:00",
      endTime: "16:20",
      mode: "Google Meet",
      type: "Veli Görüşmesi",
      title: "Efe Demir velisiyle görüşme",
      subtitle: "Devam durumu değerlendirmesi",
      isMock: true,
    },
    {
      id: "dpe-t3",
      date: "2026-08-25",
      startTime: "10:00",
      endTime: "10:30",
      mode: "Yüz yüze",
      type: "Şube Toplantısı",
      title: "Öğretmenler kurulu toplantısı",
      subtitle: "Çorlu şube",
      isMock: true,
    },
    {
      id: "dpe-t4",
      date: "2026-08-28",
      startTime: "09:00",
      endTime: "09:20",
      mode: "Google Meet",
      type: "Öğretmen Değerlendirmesi",
      title: "Dönem ortası öz değerlendirme",
      subtitle: "Akademik koordinatör ile",
      isMock: true,
    },
  ],
};

export const roleEmail: Record<Role, string> = {
  admin: "yonetici@orbit.edu.tr",
  teacher: "ogretmen@orbit.edu.tr",
  student: "ogrenci@orbit.edu.tr",
  parent: "veli@orbit.edu.tr",
};
