import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, CircleDollarSign, Mail, MessageCircle, Settings2, ShieldCheck, Users, Webhook, X } from "lucide-react";

type AutomationOption = {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: typeof Users;
  tone: string;
  fields: { key: string; label: string; placeholder: string; type?: string }[];
};

const options: AutomationOption[] = [
  { id: "lead", name: "Lead ve CRM", description: "Yeni müşteri adaylarını otomatik kaydedin.", category: "CRM", icon: Users, tone: "bg-blue-50 text-blue-700", fields: [{ key: "source", label: "Lead kaynağı", placeholder: "Form, webhook veya e-posta" }, { key: "owner", label: "Sorumlu ekip üyesi", placeholder: "Örn. Demo Kullanıcı" }] },
  { id: "appointment", name: "Randevu hatırlatma", description: "Görüşmelerden önce müşterilerinizi bilgilendirin.", category: "CRM", icon: CalendarDays, tone: "bg-violet-50 text-violet-700", fields: [{ key: "calendar", label: "Takvim kaynağı", placeholder: "Google Calendar veya Outlook" }, { key: "hours", label: "Hatırlatma süresi", placeholder: "24" }] },
  { id: "invoice", name: "Fatura hatırlatma", description: "Vadesi yaklaşan faturaları zamanında takip edin.", category: "Finans", icon: CircleDollarSign, tone: "bg-emerald-50 text-emerald-700", fields: [{ key: "days", label: "Kaç gün önce hatırlatılsın?", placeholder: "3" }, { key: "email", label: "Gönderici e-posta", placeholder: "finans@sirketiniz.com", type: "email" }] },
  { id: "expense", name: "Gider kontrolü", description: "Belgesiz veya bekleyen giderleri kaçırmayın.", category: "Finans", icon: ShieldCheck, tone: "bg-rose-50 text-rose-700", fields: [{ key: "reviewer", label: "İnceleme sorumlusu", placeholder: "Örn. Finans ekibi" }, { key: "threshold", label: "Kontrol tutarı eşiği", placeholder: "₺1.000" }] },
  { id: "webhook", name: "Webhook akışı", description: "Harici sistemlerden gelen olayları ORBIT’e bağlayın.", category: "Entegrasyon", icon: Webhook, tone: "bg-cyan-50 text-cyan-700", fields: [{ key: "url", label: "Webhook adresi", placeholder: "https://...", type: "url" }, { key: "secret", label: "Güvenlik anahtarı", placeholder: "İsteğe bağlı" }] },
  { id: "messages", name: "Müşteri mesajları", description: "Yeni talepleri CRM akışına yönlendirin.", category: "İletişim", icon: MessageCircle, tone: "bg-amber-50 text-amber-700", fields: [{ key: "channel", label: "Mesaj kanalı", placeholder: "WhatsApp, e-posta veya Instagram" }, { key: "team", label: "Atanacak ekip", placeholder: "Müşteri ilişkileri" }] },
];

export function AutomationSetupWizard({ onFinish, onSkip }: { onFinish: (selected: string[]) => void; onSkip: () => void }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [step, setStep] = useState<"select" | "details">("select");
  const [values, setValues] = useState<Record<string, string>>({});
  const selectedOptions = useMemo(() => options.filter((option) => selected.includes(option.id)), [selected]);

  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const setValue = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));

  return <main className="automation-setup-scene min-h-screen bg-[#f8fafc] px-4 py-5 text-slate-900 sm:px-8 sm:py-8">
    <header className="mx-auto flex max-w-[1120px] items-center justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-blue-600">ORBIT ilk kurulum</p><h1 className="mt-2 font-display text-[25px] font-extrabold tracking-[-0.045em] text-slate-950 sm:text-[31px]">İş akışınızı birlikte hazırlayalım</h1></div><button onClick={onSkip} aria-label="Kurulumu kapat" className="grid h-9 w-9 place-items-center rounded-lg text-slate-400 transition hover:bg-white hover:text-slate-700"><X className="h-4 w-4" /></button></header>
    <div className="mx-auto mt-7 grid max-w-[1120px] gap-6 lg:grid-cols-[1fr_300px]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,.04)] sm:p-7">
        <div className="flex items-center gap-3 border-b border-slate-100 pb-5"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-900 text-white text-[11px] font-bold">{step === "select" ? "01" : "02"}</span><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">{step === "select" ? "Otomasyon seçimi" : "Gerekli bilgiler"}</p><p className="mt-0.5 text-[12px] text-slate-500">{step === "select" ? "İşletmenize uygun akışları seçin." : "Seçtiğiniz akışların çalışması için bilgileri girin."}</p></div></div>
        {step === "select" ? <div className="mt-6 grid gap-3 sm:grid-cols-2">{options.map((option) => { const Icon = option.icon; const active = selected.includes(option.id); return <button key={option.id} onClick={() => toggle(option.id)} aria-pressed={active} className={`relative flex gap-3 rounded-xl border p-4 text-left transition ${active ? "border-blue-300 bg-blue-50/50 shadow-[0_0_0_3px_rgba(59,130,246,.08)]" : "border-slate-200 bg-white hover:border-blue-200 hover:bg-slate-50"}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${option.tone}`}><Icon className="h-4 w-4" /></span><span className="min-w-0"><span className="block text-[13px] font-bold text-slate-800">{option.name}</span><span className="mt-1 block text-[11px] leading-4 text-slate-500">{option.description}</span><span className="mt-2 block text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">{option.category}</span></span><span className={`absolute right-3 top-3 grid h-5 w-5 place-items-center rounded-full border ${active ? "border-blue-600 bg-blue-600 text-white" : "border-slate-200 text-transparent"}`}><Check className="h-3 w-3" /></span></button>; })}</div> : <div className="mt-6 space-y-5">{selectedOptions.length ? selectedOptions.map((option) => <div key={option.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><Settings2 className="h-4 w-4 text-blue-600" /><h2 className="text-[13px] font-bold text-slate-800">{option.name}</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{option.fields.map((field) => <label key={field.key} className="block"><span className="mb-1.5 block text-[10px] font-bold text-slate-500">{field.label}</span><input type={field.type ?? "text"} value={values[field.key] ?? ""} onChange={(event) => setValue(field.key, event.target.value)} placeholder={field.placeholder} className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-[12px] outline-none transition placeholder:text-slate-400 focus:border-blue-400 focus:bg-white focus:ring-3 focus:ring-blue-100" /></label>)}</div></div>) : <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 px-5 py-10 text-center"><p className="text-[12px] font-bold text-slate-700">Henüz otomasyon seçmediniz</p><p className="mt-1 text-[11px] text-slate-500">Önceki adıma dönerek bir akış seçebilirsiniz.</p></div>}</div>}
        <div className="mt-7 flex items-center justify-between border-t border-slate-100 pt-5">{step === "details" ? <button onClick={() => setStep("select")} className="flex h-10 items-center gap-2 rounded-lg px-3 text-[12px] font-bold text-slate-500 hover:bg-slate-50"><ArrowLeft className="h-4 w-4" />Geri</button> : <span />}{step === "select" ? <button onClick={() => selected.length ? setStep("details") : onSkip()} className="flex h-10 items-center gap-2 rounded-lg bg-slate-900 px-4 text-[12px] font-bold text-white shadow-sm hover:bg-slate-800">{selected.length ? "Bilgileri gir" : "Şimdilik boş bırak"}<ArrowRight className="h-4 w-4" /></button> : <button onClick={() => onFinish(selected)} className="flex h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-[12px] font-bold text-white shadow-sm hover:bg-blue-700">Kurulumu tamamla<Check className="h-4 w-4" /></button>}</div>
      </section>
      <aside className="hidden rounded-2xl border border-slate-200 bg-white p-5 lg:block"><p className="text-[11px] font-extrabold uppercase tracking-[0.12em] text-slate-400">Nasıl çalışır?</p><div className="mt-5 space-y-5">{[["01", "Seçin", "İşletmeniz için anlamlı akışları belirleyin."], ["02", "Bilgi verin", "Seçilen otomasyonların ihtiyaç duyduğu alanları doldurun."], ["03", "Başlayın", "Kurulumdan sonra akışları Otomasyonlar sayfasından yönetin."]].map(([number, title, description]) => <div key={number} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-slate-100 text-[10px] font-extrabold text-slate-500">{number}</span><div><p className="text-[12px] font-bold text-slate-700">{title}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">{description}</p></div></div>)}</div></aside>
    </div>
    <button onClick={onSkip} className="fixed bottom-4 right-4 z-20 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-[11px] font-bold text-slate-600 shadow-[0_8px_20px_rgba(15,23,42,.12)] transition hover:border-slate-400 hover:text-slate-900">Bu sayfayı geç</button>
  </main>;
}
